// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vilpdnwkfsmvqsiktqdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbHBkbndrZnNtdnFzaWt0cWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDI1MjgsImV4cCI6MjA3NDY3ODUyOH0._MU2VbX_8_aVSiLzbMQs3MWlMUoE7dFpv1P2rZNBwcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});